//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    public partial class AC03 : XPLiteObject
    {
        string fAC111;
        [Key]
        [Size(10)]
        public string AC111
        {
            get { return fAC111; }
            set { SetPropertyValue<string>(nameof(AC111), ref fAC111, value); }
        }
        string fAC001;
        [Size(10)]
        public string AC001
        {
            get { return fAC001; }
            set { SetPropertyValue<string>(nameof(AC001), ref fAC001, value); }
        }
        string fAC113;
        [Size(20)]
        public string AC113
        {
            get { return fAC113; }
            set { SetPropertyValue<string>(nameof(AC113), ref fAC113, value); }
        }
        char fAC112;
        public char AC112
        {
            get { return fAC112; }
            set { SetPropertyValue<char>(nameof(AC112), ref fAC112, value); }
        }
        int fAC114;
        public int AC114
        {
            get { return fAC114; }
            set { SetPropertyValue<int>(nameof(AC114), ref fAC114, value); }
        }
        string fAC115;
        public string AC115
        {
            get { return fAC115; }
            set { SetPropertyValue<string>(nameof(AC115), ref fAC115, value); }
        }
        DateTime fAC116;
        public DateTime AC116
        {
            get { return fAC116; }
            set { SetPropertyValue<DateTime>(nameof(AC116), ref fAC116, value); }
        }
        string fAC117;
        public string AC117
        {
            get { return fAC117; }
            set { SetPropertyValue<string>(nameof(AC117), ref fAC117, value); }
        }
        DateTime fAC118;
        public DateTime AC118
        {
            get { return fAC118; }
            set { SetPropertyValue<DateTime>(nameof(AC118), ref fAC118, value); }
        }
        DateTime fAC119;
        public DateTime AC119
        {
            get { return fAC119; }
            set { SetPropertyValue<DateTime>(nameof(AC119), ref fAC119, value); }
        }
        string fAC120;
        [Size(10)]
        public string AC120
        {
            get { return fAC120; }
            set { SetPropertyValue<string>(nameof(AC120), ref fAC120, value); }
        }
        string fAC130;
        [Size(50)]
        public string AC130
        {
            get { return fAC130; }
            set { SetPropertyValue<string>(nameof(AC130), ref fAC130, value); }
        }
        string fAC199;
        [Size(10)]
        public string AC199
        {
            get { return fAC199; }
            set { SetPropertyValue<string>(nameof(AC199), ref fAC199, value); }
        }
        char fSTATUS;
        public char STATUS
        {
            get { return fSTATUS; }
            set { SetPropertyValue<char>(nameof(STATUS), ref fSTATUS, value); }
        }
    }

}
