//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    public partial class BI01 : XPLiteObject
    {
        string fBI001;
        [Key]
        [Size(10)]
        public string BI001
        {
            get { return fBI001; }
            set { SetPropertyValue<string>(nameof(BI001), ref fBI001, value); }
        }
        int fBI002;
        public int BI002
        {
            get { return fBI002; }
            set { SetPropertyValue<int>(nameof(BI002), ref fBI002, value); }
        }
        string fBI003;
        [Size(50)]
        public string BI003
        {
            get { return fBI003; }
            set { SetPropertyValue<string>(nameof(BI003), ref fBI003, value); }
        }
        string fBI005;
        [Size(10)]
        public string BI005
        {
            get { return fBI005; }
            set { SetPropertyValue<string>(nameof(BI005), ref fBI005, value); }
        }
        decimal fPRICE;
        public decimal PRICE
        {
            get { return fPRICE; }
            set { SetPropertyValue<decimal>(nameof(PRICE), ref fPRICE, value); }
        }
        string fRG001;
        [Size(10)]
        public string RG001
        {
            get { return fRG001; }
            set { SetPropertyValue<string>(nameof(RG001), ref fRG001, value); }
        }
        string fRE001;
        [Indexed(@"BI003", Name = @"IDX_BI01_BI003", Unique = true)]
        [Size(10)]
        public string RE001
        {
            get { return fRE001; }
            set { SetPropertyValue<string>(nameof(RE001), ref fRE001, value); }
        }
        string fAC001;
        [Indexed(Name = @"IDX_BI01_AC001")]
        [Size(10)]
        public string AC001
        {
            get { return fAC001; }
            set { SetPropertyValue<string>(nameof(AC001), ref fAC001, value); }
        }
        char fSTATUS;
        [Indexed(Name = @"IDX_BI01_STATUS")]
        public char STATUS
        {
            get { return fSTATUS; }
            set { SetPropertyValue<char>(nameof(STATUS), ref fSTATUS, value); }
        }
    }

}
