//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    public partial class FA02 : XPLiteObject
    {
        string fFA001;
        [Key]
        [Size(10)]
        public string FA001
        {
            get { return fFA001; }
            set { SetPropertyValue<string>(nameof(FA001), ref fFA001, value); }
        }
        string fFA003;
        [Size(50)]
        public string FA003
        {
            get { return fFA003; }
            set { SetPropertyValue<string>(nameof(FA003), ref fFA003, value); }
        }
        string fFA100;
        [Size(10)]
        public string FA100
        {
            get { return fFA100; }
            set { SetPropertyValue<string>(nameof(FA100), ref fFA100, value); }
        }
        DateTime fFA200;
        public DateTime FA200
        {
            get { return fFA200; }
            set { SetPropertyValue<DateTime>(nameof(FA200), ref fFA200, value); }
        }
    }

}
