//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    public partial class FA03 : XPLiteObject
    {
        string fFA001;
        [Key]
        [Size(10)]
        public string FA001
        {
            get { return fFA001; }
            set { SetPropertyValue<string>(nameof(FA001), ref fFA001, value); }
        }
        string fELECNUMBER;
        [Size(50)]
        public string ELECNUMBER
        {
            get { return fELECNUMBER; }
            set { SetPropertyValue<string>(nameof(ELECNUMBER), ref fELECNUMBER, value); }
        }
    }

}
