//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    public partial class GI01 : XPLiteObject
    {
        string fGI001;
        [Key]
        [Size(10)]
        public string GI001
        {
            get { return fGI001; }
            set { SetPropertyValue<string>(nameof(GI001), ref fGI001, value); }
        }
        string fGI003;
        public string GI003
        {
            get { return fGI003; }
            set { SetPropertyValue<string>(nameof(GI003), ref fGI003, value); }
        }
        decimal fPRICE;
        public decimal PRICE
        {
            get { return fPRICE; }
            set { SetPropertyValue<decimal>(nameof(PRICE), ref fPRICE, value); }
        }
        int fSORTID;
        public int SORTID
        {
            get { return fSORTID; }
            set { SetPropertyValue<int>(nameof(SORTID), ref fSORTID, value); }
        }
        string fGI088;
        [Size(20)]
        public string GI088
        {
            get { return fGI088; }
            set { SetPropertyValue<string>(nameof(GI088), ref fGI088, value); }
        }
        string fGI099;
        [Size(10)]
        public string GI099
        {
            get { return fGI099; }
            set { SetPropertyValue<string>(nameof(GI099), ref fGI099, value); }
        }
        string fGI066;
        [Size(50)]
        public string GI066
        {
            get { return fGI066; }
            set { SetPropertyValue<string>(nameof(GI066), ref fGI066, value); }
        }
        string fGI055;
        [Size(20)]
        public string GI055
        {
            get { return fGI055; }
            set { SetPropertyValue<string>(nameof(GI055), ref fGI055, value); }
        }
        string fSTATUS;
        [Size(3)]
        public string STATUS
        {
            get { return fSTATUS; }
            set { SetPropertyValue<string>(nameof(STATUS), ref fSTATUS, value); }
        }
    }

}
