//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    [Persistent(@"LINDIAN.REGOUT")]
    public partial class LINDIAN_REGOUT : XPLiteObject
    {
        string fREASON;
        [Size(40)]
        public string REASON
        {
            get { return fREASON; }
            set { SetPropertyValue<string>(nameof(REASON), ref fREASON, value); }
        }
        decimal fFILLORRETURN;
        public decimal FILLORRETURN
        {
            get { return fFILLORRETURN; }
            set { SetPropertyValue<decimal>(nameof(FILLORRETURN), ref fFILLORRETURN, value); }
        }
        string fOUTPERSON;
        [Size(20)]
        public string OUTPERSON
        {
            get { return fOUTPERSON; }
            set { SetPropertyValue<string>(nameof(OUTPERSON), ref fOUTPERSON, value); }
        }
        int fJSLSH;
        public int JSLSH
        {
            get { return fJSLSH; }
            set { SetPropertyValue<int>(nameof(JSLSH), ref fJSLSH, value); }
        }
        int fDIFFDAYS;
        public int DIFFDAYS
        {
            get { return fDIFFDAYS; }
            set { SetPropertyValue<int>(nameof(DIFFDAYS), ref fDIFFDAYS, value); }
        }
        string fJBR;
        [Size(20)]
        public string JBR
        {
            get { return fJBR; }
            set { SetPropertyValue<string>(nameof(JBR), ref fJBR, value); }
        }
        DateTime fJBRQ;
        public DateTime JBRQ
        {
            get { return fJBRQ; }
            set { SetPropertyValue<DateTime>(nameof(JBRQ), ref fJBRQ, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(20)]
            [Persistent("REGISTER_ID")]
            public string REGISTER_ID { get; set; }
            [Persistent("OUTDATE")]
            public DateTime OUTDATE { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
