//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    [Persistent(@"LINDIAN.DISCARD")]
    public partial class LINDIAN_DISCARD : XPLiteObject
    {
        char fOPERTYPE;
        public char OPERTYPE
        {
            get { return fOPERTYPE; }
            set { SetPropertyValue<char>(nameof(OPERTYPE), ref fOPERTYPE, value); }
        }
        string fDATA1;
        [Size(50)]
        public string DATA1
        {
            get { return fDATA1; }
            set { SetPropertyValue<string>(nameof(DATA1), ref fDATA1, value); }
        }
        decimal fDATA2;
        public decimal DATA2
        {
            get { return fDATA2; }
            set { SetPropertyValue<decimal>(nameof(DATA2), ref fDATA2, value); }
        }
        string fJBR;
        [Size(20)]
        public string JBR
        {
            get { return fJBR; }
            set { SetPropertyValue<string>(nameof(JBR), ref fJBR, value); }
        }
        DateTime fJBRQ;
        public DateTime JBRQ
        {
            get { return fJBRQ; }
            set { SetPropertyValue<DateTime>(nameof(JBRQ), ref fJBRQ, value); }
        }
        string fDATA3;
        [Size(50)]
        public string DATA3
        {
            get { return fDATA3; }
            set { SetPropertyValue<string>(nameof(DATA3), ref fDATA3, value); }
        }
        decimal fDATA4;
        public decimal DATA4
        {
            get { return fDATA4; }
            set { SetPropertyValue<decimal>(nameof(DATA4), ref fDATA4, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("YWCXLSH")]
            public int YWCXLSH { get; set; }
            [Persistent("JYLSH")]
            public int JYLSH { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
