//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    [NonPersistent]
    public partial class LINDIAN_V_WARE : XPLiteObject
    {
        int fWARE_ID;
        public int WARE_ID
        {
            get { return fWARE_ID; }
            set { SetPropertyValue<int>(nameof(WARE_ID), ref fWARE_ID, value); }
        }
        string fWARE_TYPE;
        [Size(20)]
        public string WARE_TYPE
        {
            get { return fWARE_TYPE; }
            set { SetPropertyValue<string>(nameof(WARE_TYPE), ref fWARE_TYPE, value); }
        }
        string fWARE_NAME;
        [Size(50)]
        public string WARE_NAME
        {
            get { return fWARE_NAME; }
            set { SetPropertyValue<string>(nameof(WARE_NAME), ref fWARE_NAME, value); }
        }
        int fSERIAL;
        public int SERIAL
        {
            get { return fSERIAL; }
            set { SetPropertyValue<int>(nameof(SERIAL), ref fSERIAL, value); }
        }
        decimal fPRICE;
        public decimal PRICE
        {
            get { return fPRICE; }
            set { SetPropertyValue<decimal>(nameof(PRICE), ref fPRICE, value); }
        }
        string fUSEFLAG;
        [Size(3)]
        public string USEFLAG
        {
            get { return fUSEFLAG; }
            set { SetPropertyValue<string>(nameof(USEFLAG), ref fUSEFLAG, value); }
        }
        int fDATA1;
        public int DATA1
        {
            get { return fDATA1; }
            set { SetPropertyValue<int>(nameof(DATA1), ref fDATA1, value); }
        }
        string fDATA2;
        [Size(50)]
        public string DATA2
        {
            get { return fDATA2; }
            set { SetPropertyValue<string>(nameof(DATA2), ref fDATA2, value); }
        }
    }

}
