//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    [Persistent(@"LINDIAN.BIT")]
    public partial class LINDIAN_BIT : XPLiteObject
    {
        int fREGIONID;
        [Indexed(Name = @"IDX_BIT_REGIONID")]
        public int REGIONID
        {
            get { return fREGIONID; }
            set { SetPropertyValue<int>(nameof(REGIONID), ref fREGIONID, value); }
        }
        int fLAYERID;
        public int LAYERID
        {
            get { return fLAYERID; }
            set { SetPropertyValue<int>(nameof(LAYERID), ref fLAYERID, value); }
        }
        int fHALLID;
        public int HALLID
        {
            get { return fHALLID; }
            set { SetPropertyValue<int>(nameof(HALLID), ref fHALLID, value); }
        }
        int fFLOORID;
        public int FLOORID
        {
            get { return fFLOORID; }
            set { SetPropertyValue<int>(nameof(FLOORID), ref fFLOORID, value); }
        }
        decimal fFIXPRICE;
        [ColumnDbDefaultValue("0")]
        public decimal FIXPRICE
        {
            get { return fFIXPRICE; }
            set { SetPropertyValue<decimal>(nameof(FIXPRICE), ref fFIXPRICE, value); }
        }
        char fBITSTATUS;
        public char BITSTATUS
        {
            get { return fBITSTATUS; }
            set { SetPropertyValue<char>(nameof(BITSTATUS), ref fBITSTATUS, value); }
        }
        string fBITDESC;
        public string BITDESC
        {
            get { return fBITDESC; }
            set { SetPropertyValue<string>(nameof(BITDESC), ref fBITDESC, value); }
        }
        string fREGISTERID;
        [Indexed(Name = @"IDX_BIT_REGISTERID")]
        [Size(20)]
        public string REGISTERID
        {
            get { return fREGISTERID; }
            set { SetPropertyValue<string>(nameof(REGISTERID), ref fREGISTERID, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("ROOMID")]
            public int ROOMID { get; set; }
            [Persistent("BITID")]
            public int BITID { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
