//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    [Persistent(@"LINDIAN.T_VERSION")]
    public partial class LINDIAN_T_VERSION : XPLiteObject
    {
        DateTime fPUBLISH_DATE;
        public DateTime PUBLISH_DATE
        {
            get { return fPUBLISH_DATE; }
            set { SetPropertyValue<DateTime>(nameof(PUBLISH_DATE), ref fPUBLISH_DATE, value); }
        }
        string fVERSION_DESC;
        [Size(250)]
        public string VERSION_DESC
        {
            get { return fVERSION_DESC; }
            set { SetPropertyValue<string>(nameof(VERSION_DESC), ref fVERSION_DESC, value); }
        }
        char fFORCE;
        public char FORCE
        {
            get { return fFORCE; }
            set { SetPropertyValue<char>(nameof(FORCE), ref fFORCE, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("VERSION_NUM")]
            public decimal VERSION_NUM { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
