//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    [NonPersistent]
    public partial class LINDIAN_V_ALL_WARE : XPLiteObject
    {
        string fCODE_VALUE;
        [Size(50)]
        public string CODE_VALUE
        {
            get { return fCODE_VALUE; }
            set { SetPropertyValue<string>(nameof(CODE_VALUE), ref fCODE_VALUE, value); }
        }
        string fCODE_VALUE_DESC;
        [Size(50)]
        public string CODE_VALUE_DESC
        {
            get { return fCODE_VALUE_DESC; }
            set { SetPropertyValue<string>(nameof(CODE_VALUE_DESC), ref fCODE_VALUE_DESC, value); }
        }
    }

}
