//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    [Persistent(@"LINDIAN.PAYRECORD")]
    public partial class LINDIAN_PAYRECORD : XPLiteObject
    {
        string fREGISTER_ID;
        [Indexed(Name = @"IDX_PAYRECORD_REGISTER_ID")]
        [Size(20)]
        public string REGISTER_ID
        {
            get { return fREGISTER_ID; }
            set { SetPropertyValue<string>(nameof(REGISTER_ID), ref fREGISTER_ID, value); }
        }
        int fNUMS;
        public int NUMS
        {
            get { return fNUMS; }
            set { SetPropertyValue<int>(nameof(NUMS), ref fNUMS, value); }
        }
        decimal fPRICE;
        public decimal PRICE
        {
            get { return fPRICE; }
            set { SetPropertyValue<decimal>(nameof(PRICE), ref fPRICE, value); }
        }
        decimal fREGMONEY;
        public decimal REGMONEY
        {
            get { return fREGMONEY; }
            set { SetPropertyValue<decimal>(nameof(REGMONEY), ref fREGMONEY, value); }
        }
        decimal fATTACHMONEY;
        public decimal ATTACHMONEY
        {
            get { return fATTACHMONEY; }
            set { SetPropertyValue<decimal>(nameof(ATTACHMONEY), ref fATTACHMONEY, value); }
        }
        int fPAYMONEY;
        public int PAYMONEY
        {
            get { return fPAYMONEY; }
            set { SetPropertyValue<int>(nameof(PAYMONEY), ref fPAYMONEY, value); }
        }
        decimal fREALPAY;
        public decimal REALPAY
        {
            get { return fREALPAY; }
            set { SetPropertyValue<decimal>(nameof(REALPAY), ref fREALPAY, value); }
        }
        DateTime fBEGINTIME;
        public DateTime BEGINTIME
        {
            get { return fBEGINTIME; }
            set { SetPropertyValue<DateTime>(nameof(BEGINTIME), ref fBEGINTIME, value); }
        }
        DateTime fENDATE;
        public DateTime ENDATE
        {
            get { return fENDATE; }
            set { SetPropertyValue<DateTime>(nameof(ENDATE), ref fENDATE, value); }
        }
        string fPAYFLAG;
        [Size(3)]
        public string PAYFLAG
        {
            get { return fPAYFLAG; }
            set { SetPropertyValue<string>(nameof(PAYFLAG), ref fPAYFLAG, value); }
        }
        string fPAYTYPE;
        [Indexed(Name = @"IDX_PAYRECORD_PAYTYPE")]
        [Size(3)]
        public string PAYTYPE
        {
            get { return fPAYTYPE; }
            set { SetPropertyValue<string>(nameof(PAYTYPE), ref fPAYTYPE, value); }
        }
        int fJSLSH;
        [Indexed(Name = @"IDX_PAYRECORD_JSLSH")]
        public int JSLSH
        {
            get { return fJSLSH; }
            set { SetPropertyValue<int>(nameof(JSLSH), ref fJSLSH, value); }
        }
        int fJBR;
        public int JBR
        {
            get { return fJBR; }
            set { SetPropertyValue<int>(nameof(JBR), ref fJBR, value); }
        }
        DateTime fJBRQ;
        public DateTime JBRQ
        {
            get { return fJBRQ; }
            set { SetPropertyValue<DateTime>(nameof(JBRQ), ref fJBRQ, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("JYLSH")]
            public int JYLSH { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
