//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    [NonPersistent]
    public partial class LINDIAN_V_FINANCE : XPLiteObject
    {
        int fJSLSH;
        public int JSLSH
        {
            get { return fJSLSH; }
            set { SetPropertyValue<int>(nameof(JSLSH), ref fJSLSH, value); }
        }
        string fFEETYPE;
        [Size(3)]
        public string FEETYPE
        {
            get { return fFEETYPE; }
            set { SetPropertyValue<string>(nameof(FEETYPE), ref fFEETYPE, value); }
        }
        decimal fFEE;
        public decimal FEE
        {
            get { return fFEE; }
            set { SetPropertyValue<decimal>(nameof(FEE), ref fFEE, value); }
        }
        string fFEEFLAG;
        [Size(3)]
        public string FEEFLAG
        {
            get { return fFEEFLAG; }
            set { SetPropertyValue<string>(nameof(FEEFLAG), ref fFEEFLAG, value); }
        }
        int fJBR;
        public int JBR
        {
            get { return fJBR; }
            set { SetPropertyValue<int>(nameof(JBR), ref fJBR, value); }
        }
        DateTime fJBRQ;
        public DateTime JBRQ
        {
            get { return fJBRQ; }
            set { SetPropertyValue<DateTime>(nameof(JBRQ), ref fJBRQ, value); }
        }
        string fJKR;
        [Size(20)]
        public string JKR
        {
            get { return fJKR; }
            set { SetPropertyValue<string>(nameof(JKR), ref fJKR, value); }
        }
        string fSPR;
        [Size(20)]
        public string SPR
        {
            get { return fSPR; }
            set { SetPropertyValue<string>(nameof(SPR), ref fSPR, value); }
        }
    }

}
