//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    [Persistent(@"LINDIAN.FLOOR")]
    public partial class LINDIAN_FLOOR : XPLiteObject
    {
        int fHALLID;
        public int HALLID
        {
            get { return fHALLID; }
            set { SetPropertyValue<int>(nameof(HALLID), ref fHALLID, value); }
        }
        string fFLOORDESC;
        [Size(50)]
        public string FLOORDESC
        {
            get { return fFLOORDESC; }
            set { SetPropertyValue<string>(nameof(FLOORDESC), ref fFLOORDESC, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("FLOORID")]
            public int FLOORID { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
