//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    [Persistent(@"LINDIAN.OPERATOR")]
    public partial class LINDIAN_OPERATOR : XPLiteObject
    {
        string fOPERATOR_CODE;
        [Size(20)]
        public string OPERATOR_CODE
        {
            get { return fOPERATOR_CODE; }
            set { SetPropertyValue<string>(nameof(OPERATOR_CODE), ref fOPERATOR_CODE, value); }
        }
        string fOPERATOR_DESC;
        [Size(50)]
        public string OPERATOR_DESC
        {
            get { return fOPERATOR_DESC; }
            set { SetPropertyValue<string>(nameof(OPERATOR_DESC), ref fOPERATOR_DESC, value); }
        }
        int fGROUP_ID;
        public int GROUP_ID
        {
            get { return fGROUP_ID; }
            set { SetPropertyValue<int>(nameof(GROUP_ID), ref fGROUP_ID, value); }
        }
        string fPASSWD;
        [Size(50)]
        public string PASSWD
        {
            get { return fPASSWD; }
            set { SetPropertyValue<string>(nameof(PASSWD), ref fPASSWD, value); }
        }
        char fOPERATOR_FLAG;
        public char OPERATOR_FLAG
        {
            get { return fOPERATOR_FLAG; }
            set { SetPropertyValue<char>(nameof(OPERATOR_FLAG), ref fOPERATOR_FLAG, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("OPERATOR_ID")]
            public int OPERATOR_ID { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
