//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    [NonPersistent]
    public partial class LINDIAN_V_DICT : XPLiteObject
    {
        int fDICTID;
        public int DICTID
        {
            get { return fDICTID; }
            set { SetPropertyValue<int>(nameof(DICTID), ref fDICTID, value); }
        }
        string fDICT_TYPE;
        [Size(20)]
        public string DICT_TYPE
        {
            get { return fDICT_TYPE; }
            set { SetPropertyValue<string>(nameof(DICT_TYPE), ref fDICT_TYPE, value); }
        }
        string fDICT_TYPE_DESC;
        [Size(50)]
        public string DICT_TYPE_DESC
        {
            get { return fDICT_TYPE_DESC; }
            set { SetPropertyValue<string>(nameof(DICT_TYPE_DESC), ref fDICT_TYPE_DESC, value); }
        }
        string fDICT_VALUE_TYPE;
        [Size(3)]
        public string DICT_VALUE_TYPE
        {
            get { return fDICT_VALUE_TYPE; }
            set { SetPropertyValue<string>(nameof(DICT_VALUE_TYPE), ref fDICT_VALUE_TYPE, value); }
        }
        string fDICT_ITEM1;
        [Size(50)]
        public string DICT_ITEM1
        {
            get { return fDICT_ITEM1; }
            set { SetPropertyValue<string>(nameof(DICT_ITEM1), ref fDICT_ITEM1, value); }
        }
        decimal fDICT_ITEM2;
        public decimal DICT_ITEM2
        {
            get { return fDICT_ITEM2; }
            set { SetPropertyValue<decimal>(nameof(DICT_ITEM2), ref fDICT_ITEM2, value); }
        }
        string fUSEFLAG;
        [Size(3)]
        public string USEFLAG
        {
            get { return fUSEFLAG; }
            set { SetPropertyValue<string>(nameof(USEFLAG), ref fUSEFLAG, value); }
        }
        int fDATA1;
        public int DATA1
        {
            get { return fDATA1; }
            set { SetPropertyValue<int>(nameof(DATA1), ref fDATA1, value); }
        }
        string fDATA2;
        [Size(50)]
        public string DATA2
        {
            get { return fDATA2; }
            set { SetPropertyValue<string>(nameof(DATA2), ref fDATA2, value); }
        }
    }

}
