//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    public partial class REFUND : XPLiteObject
    {
        string fRF001;
        [Key]
        [Size(10)]
        public string RF001
        {
            get { return fRF001; }
            set { SetPropertyValue<string>(nameof(RF001), ref fRF001, value); }
        }
        decimal fRF004;
        public decimal RF004
        {
            get { return fRF004; }
            set { SetPropertyValue<decimal>(nameof(RF004), ref fRF004, value); }
        }
        string fRF003;
        [Size(200)]
        public string RF003
        {
            get { return fRF003; }
            set { SetPropertyValue<string>(nameof(RF003), ref fRF003, value); }
        }
        string fRF100;
        [Size(10)]
        public string RF100
        {
            get { return fRF100; }
            set { SetPropertyValue<string>(nameof(RF100), ref fRF100, value); }
        }
        DateTime fRF200;
        public DateTime RF200
        {
            get { return fRF200; }
            set { SetPropertyValue<DateTime>(nameof(RF200), ref fRF200, value); }
        }
        string fRF300;
        [Size(10)]
        public string RF300
        {
            get { return fRF300; }
            set { SetPropertyValue<string>(nameof(RF300), ref fRF300, value); }
        }
    }

}
