//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    public partial class RG01 : XPLiteObject
    {
        string fRG001;
        [Key]
        [Size(10)]
        public string RG001
        {
            get { return fRG001; }
            set { SetPropertyValue<string>(nameof(RG001), ref fRG001, value); }
        }
        char fRG002;
        public char RG002
        {
            get { return fRG002; }
            set { SetPropertyValue<char>(nameof(RG002), ref fRG002, value); }
        }
        string fRG003;
        [Size(50)]
        public string RG003
        {
            get { return fRG003; }
            set { SetPropertyValue<string>(nameof(RG003), ref fRG003, value); }
        }
        string fRG004;
        [Size(10)]
        public string RG004
        {
            get { return fRG004; }
            set { SetPropertyValue<string>(nameof(RG004), ref fRG004, value); }
        }
        int fRG005;
        public int RG005
        {
            get { return fRG005; }
            set { SetPropertyValue<int>(nameof(RG005), ref fRG005, value); }
        }
        int fRG006;
        public int RG006
        {
            get { return fRG006; }
            set { SetPropertyValue<int>(nameof(RG006), ref fRG006, value); }
        }
        char fRG007;
        public char RG007
        {
            get { return fRG007; }
            set { SetPropertyValue<char>(nameof(RG007), ref fRG007, value); }
        }
        string fRG009;
        [Size(10)]
        public string RG009
        {
            get { return fRG009; }
            set { SetPropertyValue<string>(nameof(RG009), ref fRG009, value); }
        }
        decimal fPRICE;
        public decimal PRICE
        {
            get { return fPRICE; }
            set { SetPropertyValue<decimal>(nameof(PRICE), ref fPRICE, value); }
        }
    }

}
