//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    public partial class SI01 : XPLiteObject
    {
        string fSI001;
        [Key]
        [Size(10)]
        public string SI001
        {
            get { return fSI001; }
            set { SetPropertyValue<string>(nameof(SI001), ref fSI001, value); }
        }
        string fSI003;
        public string SI003
        {
            get { return fSI003; }
            set { SetPropertyValue<string>(nameof(SI003), ref fSI003, value); }
        }
        decimal fPRICE;
        public decimal PRICE
        {
            get { return fPRICE; }
            set { SetPropertyValue<decimal>(nameof(PRICE), ref fPRICE, value); }
        }
        int fSORTID;
        public int SORTID
        {
            get { return fSORTID; }
            set { SetPropertyValue<int>(nameof(SORTID), ref fSORTID, value); }
        }
        string fSI088;
        [Size(20)]
        public string SI088
        {
            get { return fSI088; }
            set { SetPropertyValue<string>(nameof(SI088), ref fSI088, value); }
        }
        string fSI099;
        [Size(10)]
        public string SI099
        {
            get { return fSI099; }
            set { SetPropertyValue<string>(nameof(SI099), ref fSI099, value); }
        }
        string fSI066;
        [Size(50)]
        public string SI066
        {
            get { return fSI066; }
            set { SetPropertyValue<string>(nameof(SI066), ref fSI066, value); }
        }
        string fSI055;
        [Size(20)]
        public string SI055
        {
            get { return fSI055; }
            set { SetPropertyValue<string>(nameof(SI055), ref fSI055, value); }
        }
        string fSTATUS;
        [Size(3)]
        public string STATUS
        {
            get { return fSTATUS; }
            set { SetPropertyValue<string>(nameof(STATUS), ref fSTATUS, value); }
        }
    }

}
