//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    public partial class ST01 : XPLiteObject
    {
        string fST001;
        [Key]
        [Size(10)]
        public string ST001
        {
            get { return fST001; }
            set { SetPropertyValue<string>(nameof(ST001), ref fST001, value); }
        }
        string fST002;
        [Size(15)]
        public string ST002
        {
            get { return fST002; }
            set { SetPropertyValue<string>(nameof(ST002), ref fST002, value); }
        }
        string fST003;
        public string ST003
        {
            get { return fST003; }
            set { SetPropertyValue<string>(nameof(ST003), ref fST003, value); }
        }
        int fSORTID;
        public int SORTID
        {
            get { return fSORTID; }
            set { SetPropertyValue<int>(nameof(SORTID), ref fSORTID, value); }
        }
        string fSTATUS;
        [Size(3)]
        public string STATUS
        {
            get { return fSTATUS; }
            set { SetPropertyValue<string>(nameof(STATUS), ref fSTATUS, value); }
        }
    }

}
