//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    public partial class TR01 : XPLiteObject
    {
        string fTR001;
        [Key]
        [Size(10)]
        public string TR001
        {
            get { return fTR001; }
            set { SetPropertyValue<string>(nameof(TR001), ref fTR001, value); }
        }
        string fAC001;
        [Size(10)]
        public string AC001
        {
            get { return fAC001; }
            set { SetPropertyValue<string>(nameof(AC001), ref fAC001, value); }
        }
        string fTR002;
        [Size(10)]
        public string TR002
        {
            get { return fTR002; }
            set { SetPropertyValue<string>(nameof(TR002), ref fTR002, value); }
        }
        string fTR003;
        [Size(10)]
        public string TR003
        {
            get { return fTR003; }
            set { SetPropertyValue<string>(nameof(TR003), ref fTR003, value); }
        }
        string fTR005;
        public string TR005
        {
            get { return fTR005; }
            set { SetPropertyValue<string>(nameof(TR005), ref fTR005, value); }
        }
        string fTR100;
        [Size(10)]
        public string TR100
        {
            get { return fTR100; }
            set { SetPropertyValue<string>(nameof(TR100), ref fTR100, value); }
        }
        DateTime fTR200;
        public DateTime TR200
        {
            get { return fTR200; }
            set { SetPropertyValue<DateTime>(nameof(TR200), ref fTR200, value); }
        }
    }

}
