//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    public partial class V_ALL_VALIDITEM : XPLiteObject
    {
        string fITEM_ID;
        [Key]
        [Size(10)]
        public string ITEM_ID
        {
            get { return fITEM_ID; }
            set { SetPropertyValue<string>(nameof(ITEM_ID), ref fITEM_ID, value); }
        }
        char fITEM_TYPE;
        public char ITEM_TYPE
        {
            get { return fITEM_TYPE; }
            set { SetPropertyValue<char>(nameof(ITEM_TYPE), ref fITEM_TYPE, value); }
        }
        string fITEM_NAME;
        public string ITEM_NAME
        {
            get { return fITEM_NAME; }
            set { SetPropertyValue<string>(nameof(ITEM_NAME), ref fITEM_NAME, value); }
        }
        decimal fPRICE;
        public decimal PRICE
        {
            get { return fPRICE; }
            set { SetPropertyValue<decimal>(nameof(PRICE), ref fPRICE, value); }
        }
        int fSORTID;
        public int SORTID
        {
            get { return fSORTID; }
            set { SetPropertyValue<int>(nameof(SORTID), ref fSORTID, value); }
        }
        string fZJF;
        [Size(20)]
        public string ZJF
        {
            get { return fZJF; }
            set { SetPropertyValue<string>(nameof(ZJF), ref fZJF, value); }
        }
        string fINV_CODE;
        [Size(10)]
        public string INV_CODE
        {
            get { return fINV_CODE; }
            set { SetPropertyValue<string>(nameof(INV_CODE), ref fINV_CODE, value); }
        }
        string fITEM_GGXH;
        [Size(50)]
        public string ITEM_GGXH
        {
            get { return fITEM_GGXH; }
            set { SetPropertyValue<string>(nameof(ITEM_GGXH), ref fITEM_GGXH, value); }
        }
        string fITEM_JLDW;
        [Size(20)]
        public string ITEM_JLDW
        {
            get { return fITEM_JLDW; }
            set { SetPropertyValue<string>(nameof(ITEM_JLDW), ref fITEM_JLDW, value); }
        }
        int fTAXRATE;
        public int TAXRATE
        {
            get { return fTAXRATE; }
            set { SetPropertyValue<int>(nameof(TAXRATE), ref fTAXRATE, value); }
        }
    }

}
