//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    public partial class V_BK01_LIST : XPLiteObject
    {
        string fBK001;
        [Key]
        [Size(10)]
        public string BK001
        {
            get { return fBK001; }
            set { SetPropertyValue<string>(nameof(BK001), ref fBK001, value); }
        }
        string fPOSITION;
        [Size(4000)]
        public string POSITION
        {
            get { return fPOSITION; }
            set { SetPropertyValue<string>(nameof(POSITION), ref fPOSITION, value); }
        }
        string fBK003;
        [Size(50)]
        public string BK003
        {
            get { return fBK003; }
            set { SetPropertyValue<string>(nameof(BK003), ref fBK003, value); }
        }
        DateTime fBK009;
        public DateTime BK009
        {
            get { return fBK009; }
            set { SetPropertyValue<DateTime>(nameof(BK009), ref fBK009, value); }
        }
        string fBK005;
        [Size(50)]
        public string BK005
        {
            get { return fBK005; }
            set { SetPropertyValue<string>(nameof(BK005), ref fBK005, value); }
        }
        string fBK100;
        [Size(10)]
        public string BK100
        {
            get { return fBK100; }
            set { SetPropertyValue<string>(nameof(BK100), ref fBK100, value); }
        }
        DateTime fBK200;
        public DateTime BK200
        {
            get { return fBK200; }
            set { SetPropertyValue<DateTime>(nameof(BK200), ref fBK200, value); }
        }
        char fSTATUS;
        public char STATUS
        {
            get { return fSTATUS; }
            set { SetPropertyValue<char>(nameof(STATUS), ref fSTATUS, value); }
        }
    }

}
