//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

	public partial class V_FA01_SEARCH : XPLiteObject
	{
		string fFA001;
		[Key]
		[Size(10)]
		public string FA001
		{
			get { return fFA001; }
			set { SetPropertyValue<string>(nameof(FA001), ref fFA001, value); }
		}
		char fFA002;
		public char FA002
		{
			get { return fFA002; }
			set { SetPropertyValue<char>(nameof(FA002), ref fFA002, value); }
		}
		string fAC001;
		[Size(10)]
		public string AC001
		{
			get { return fAC001; }
			set { SetPropertyValue<string>(nameof(AC001), ref fAC001, value); }
		}
		string fFA003;
		[Size(50)]
		public string FA003
		{
			get { return fFA003; }
			set { SetPropertyValue<string>(nameof(FA003), ref fFA003, value); }
		}
		decimal fFA004;
		public decimal FA004
		{
			get { return fFA004; }
			set { SetPropertyValue<decimal>(nameof(FA004), ref fFA004, value); }
		}
		string fFA180;
		public string FA180
		{
			get { return fFA180; }
			set { SetPropertyValue<string>(nameof(FA180), ref fFA180, value); }
		}
		char fFA190;
		public char FA190
		{
			get { return fFA190; }
			set { SetPropertyValue<char>(nameof(FA190), ref fFA190, value); }
		}
		string fFA100;
		[Size(10)]
		public string FA100
		{
			get { return fFA100; }
			set { SetPropertyValue<string>(nameof(FA100), ref fFA100, value); }
		}
		string fHANDLER;
		[Size(4000)]
		public string HANDLER
		{
			get { return fHANDLER; }
			set { SetPropertyValue<string>(nameof(HANDLER), ref fHANDLER, value); }
		}
		DateTime fFA200;
		public DateTime FA200
		{
			get { return fFA200; }
			set { SetPropertyValue<DateTime>(nameof(FA200), ref fFA200, value); }
		}
		string fWS001;
		[Size(10)]
		public string WS001
		{
			get { return fWS001; }
			set { SetPropertyValue<string>(nameof(WS001), ref fWS001, value); }
		}
		string fINVNUM;
		[Size(4000)]
		public string INVNUM
		{
			get { return fINVNUM; }
			set { SetPropertyValue<string>(nameof(INVNUM), ref fINVNUM, value); }
		}
		string fWS003;
		[Size(4000)]
		public string WS003
		{
			get { return fWS003; }
			set { SetPropertyValue<string>(nameof(WS003), ref fWS003, value); }
		}
		string fPOSITION;
		public string POSITION
		{
			get { return fPOSITION; }
			set { SetPropertyValue<string>(nameof(POSITION), ref fPOSITION, value); }
		}
	}

}
