//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    [NonPersistent]
    public partial class V_HAVE_INVOICED : XPLiteObject
    {
        string fINVOICECODE;
        [Size(50)]
        public string INVOICECODE
        {
            get { return fINVOICECODE; }
            set { SetPropertyValue<string>(nameof(INVOICECODE), ref fINVOICECODE, value); }
        }
        string fINVOICENUM;
        [Size(50)]
        public string INVOICENUM
        {
            get { return fINVOICENUM; }
            set { SetPropertyValue<string>(nameof(INVOICENUM), ref fINVOICENUM, value); }
        }
        decimal fJSHJ;
        public decimal JSHJ
        {
            get { return fJSHJ; }
            set { SetPropertyValue<decimal>(nameof(JSHJ), ref fJSHJ, value); }
        }
        DateTime fINVOICEDATE;
        public DateTime INVOICEDATE
        {
            get { return fINVOICEDATE; }
            set { SetPropertyValue<DateTime>(nameof(INVOICEDATE), ref fINVOICEDATE, value); }
        }
        string fFA001;
        [Size(10)]
        public string FA001
        {
            get { return fFA001; }
            set { SetPropertyValue<string>(nameof(FA001), ref fFA001, value); }
        }
    }

}
