//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    [NonPersistent]
    public partial class V_PRINT_CERT : XPLiteObject
    {
        string fAC001;
        [Size(10)]
        public string AC001
        {
            get { return fAC001; }
            set { SetPropertyValue<string>(nameof(AC001), ref fAC001, value); }
        }
        string fAC003;
        [Size(50)]
        public string AC003
        {
            get { return fAC003; }
            set { SetPropertyValue<string>(nameof(AC003), ref fAC003, value); }
        }
        string fAC005;
        public string AC005
        {
            get { return fAC005; }
            set { SetPropertyValue<string>(nameof(AC005), ref fAC005, value); }
        }
        string fPOSITION;
        [Size(4000)]
        public string POSITION
        {
            get { return fPOSITION; }
            set { SetPropertyValue<string>(nameof(POSITION), ref fPOSITION, value); }
        }
        string fAC113;
        [Size(20)]
        public string AC113
        {
            get { return fAC113; }
            set { SetPropertyValue<string>(nameof(AC113), ref fAC113, value); }
        }
        char fAC112;
        public char AC112
        {
            get { return fAC112; }
            set { SetPropertyValue<char>(nameof(AC112), ref fAC112, value); }
        }
        int fAC114;
        public int AC114
        {
            get { return fAC114; }
            set { SetPropertyValue<int>(nameof(AC114), ref fAC114, value); }
        }
        string fAC115;
        public string AC115
        {
            get { return fAC115; }
            set { SetPropertyValue<string>(nameof(AC115), ref fAC115, value); }
        }
        DateTime fAC116;
        public DateTime AC116
        {
            get { return fAC116; }
            set { SetPropertyValue<DateTime>(nameof(AC116), ref fAC116, value); }
        }
        DateTime fAC118;
        public DateTime AC118
        {
            get { return fAC118; }
            set { SetPropertyValue<DateTime>(nameof(AC118), ref fAC118, value); }
        }
        DateTime fAC119;
        public DateTime AC119
        {
            get { return fAC119; }
            set { SetPropertyValue<DateTime>(nameof(AC119), ref fAC119, value); }
        }
        DateTime fAC049;
        public DateTime AC049
        {
            get { return fAC049; }
            set { SetPropertyValue<DateTime>(nameof(AC049), ref fAC049, value); }
        }
        string fAC050;
        [Size(15)]
        public string AC050
        {
            get { return fAC050; }
            set { SetPropertyValue<string>(nameof(AC050), ref fAC050, value); }
        }
    }

}
