//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    public partial class V_REPORT_TOMBDATA_UNSALED : XPLiteObject
    {
        string fBI001;
        [Key]
        [Size(10)]
        public string BI001
        {
            get { return fBI001; }
            set { SetPropertyValue<string>(nameof(BI001), ref fBI001, value); }
        }
        string fPOSITION;
        [Size(4000)]
        public string POSITION
        {
            get { return fPOSITION; }
            set { SetPropertyValue<string>(nameof(POSITION), ref fPOSITION, value); }
        }
        decimal fPRICE;
        public decimal PRICE
        {
            get { return fPRICE; }
            set { SetPropertyValue<decimal>(nameof(PRICE), ref fPRICE, value); }
        }
        string fBI005;
        [Size(4000)]
        public string BI005
        {
            get { return fBI005; }
            set { SetPropertyValue<string>(nameof(BI005), ref fBI005, value); }
        }
        string fRG001;
        [Size(10)]
        public string RG001
        {
            get { return fRG001; }
            set { SetPropertyValue<string>(nameof(RG001), ref fRG001, value); }
        }
    }

}
