//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    public partial class V_REPORT_TOMBCANCEL : XPLiteObject
    {
        string fAC001;
        [Key]
        [Size(10)]
        public string AC001
        {
            get { return fAC001; }
            set { SetPropertyValue<string>(nameof(AC001), ref fAC001, value); }
        }
        string fAC003;
        [Size(50)]
        public string AC003
        {
            get { return fAC003; }
            set { SetPropertyValue<string>(nameof(AC003), ref fAC003, value); }
        }
        string fPOSITION;
        [Size(4000)]
        public string POSITION
        {
            get { return fPOSITION; }
            set { SetPropertyValue<string>(nameof(POSITION), ref fPOSITION, value); }
        }
        DateTime fAC049;
        public DateTime AC049
        {
            get { return fAC049; }
            set { SetPropertyValue<DateTime>(nameof(AC049), ref fAC049, value); }
        }
        string fFA001;
        [Size(10)]
        public string FA001
        {
            get { return fFA001; }
            set { SetPropertyValue<string>(nameof(FA001), ref fFA001, value); }
        }
        DateTime fFA200;
        public DateTime FA200
        {
            get { return fFA200; }
            set { SetPropertyValue<DateTime>(nameof(FA200), ref fFA200, value); }
        }
        decimal fAC022;
        public decimal AC022
        {
            get { return fAC022; }
            set { SetPropertyValue<decimal>(nameof(AC022), ref fAC022, value); }
        }
        int fFA004;
        public int FA004
        {
            get { return fFA004; }
            set { SetPropertyValue<int>(nameof(FA004), ref fFA004, value); }
        }
    }

}
