//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace green.xpo.orcl
{

    public partial class WS01 : XPLiteObject
    {
        string fWS001;
        [Key]
        [Size(10)]
        public string WS001
        {
            get { return fWS001; }
            set { SetPropertyValue<string>(nameof(WS001), ref fWS001, value); }
        }
        string fWS003;
        [Size(50)]
        public string WS003
        {
            get { return fWS003; }
            set { SetPropertyValue<string>(nameof(WS003), ref fWS003, value); }
        }
        string fWS005;
        [Size(50)]
        public string WS005
        {
            get { return fWS005; }
            set { SetPropertyValue<string>(nameof(WS005), ref fWS005, value); }
        }
        string fWS007;
        [Size(20)]
        public string WS007
        {
            get { return fWS007; }
            set { SetPropertyValue<string>(nameof(WS007), ref fWS007, value); }
        }
        char fSTATUS;
        public char STATUS
        {
            get { return fSTATUS; }
            set { SetPropertyValue<char>(nameof(STATUS), ref fSTATUS, value); }
        }
    }

}
